### PR TITLE
Preliminary c++ function definitions for review

### PR DESCRIPTION
**Pull request by andrewCodeDev**
Hey Sarah, I wrote a first draft for the thesaurus! I have a few thoughts and questions I'd like to discuss :)

In the definitions, I have often written something like:

> void foo() { // function body - return statement is optional }

The "// function body - return statement is optional " part is written as such because there is some ambiguity regarding when a return statement is necessary. If you would like, I can remove these and give more direct examples but it would be less generic.

If you want the formatting changed or if I've made some mistake, let me know and I'll be happy to fix it.

### CODE REVIEW

**Comment by andrewCodeDev** [comment]
Hey Sarah, have you gotten a chance to look at this yet? There was a Django test failure but I'm not sure if that was from my contribution or not - can you review my questions in the pull request?

**Comment by geekygirlsarah** [comment]
Hey @andrewCodeDev! I'm not sure why but I never got an email notification for this and just never saw it show up.

I'm a little torn because I appreciate the contributions here (especially with templates and anonymous functions in C++), but this should really be PR'd against the original repo (https://github.com/codethesaurus/codethesaur.us/), not my fork of it.

Would you mind redoing the PR against codethesaurus/codethesaur.us? And if you need help figuring out how, let me know as there might be merge conflicts possibly... 😬

**Comment by andrewCodeDev** [comment]
Hey Sarah - no prob regarding the timing. I'd be happy to move my PR over to the main branch.

That said, am I syntactically close to what is required? I'm not particularly familiar with the required format so if you could double check my approach then I'd be happy to move the PR.

**Comment by geekygirlsarah** [comment]
It's pretty close! The changes needed would be:

- Remove all "name" fields. (This is optional but they no longer have a purpose.)
- Any newlines need `\n` in the string where they are. I know C++ doesn't require them, but almost everyone writes them on separate lines so you may want to consider that. Spaces are preserved on displaying, and things are now syntax highlighted
- Though having comments makes sense, there's now a `"comment: "..."` field you can add to each. So instead of trying to clarify within the code, move clarifications to comments instead.
- And you'll need to do a `git pull` into this. I don't know that it will do a merge conflict or not but just be aware just in case it might.

ex:
```
    "anonymous_function_variable_parameters": {
      "code": "[](auto ... args){\n    statementsOrFunctions();\n    }",
      "comment": "Function body will return the type deduced from the optional return statement."
    },
```

And again, if you want help with any of that PR migration or local migration to codethesaurus/codethesaur.us, let me know!

**Comment by andrewCodeDev** [comment]
Awesome - thank you, Sarah. 

I'll modify this later tonight and get started on that pull.

**Comment by geekygirlsarah** [comment]
I'm closing this because it was opened against my fork and not against the organization's repo. (If the changes are still valid, you can still open a new PR against that one)

**Pull request closed without merging**
